yiBot/main/urls.py
from django.urls import path

from main import views

app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
]

yiBot/yiBot/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from lineBot import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('lineBot/', include('lineBot.urls', namespace='lineBot')),
    path('lottery/', include('lottery.urls', namespace='lottery')),
    path('todoList/', include('todoList.urls', namespace='todoList')),
    path('main/', include('main.urls', namespace='main')),
    re_path('.*', views.lineBot)
]

yiBot/main/models.py
from django.db import models

# Create your models here.

yiBot/main/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
    return render(request, 'main/main.html', {})

yiBot/main/templates/main/main.html
<!doctype html>
{% load static %}
<html>
<head>
<title>YiBot</title>
<meta charset=utf-8>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel=stylesheet href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<link rel=stylesheet href="{% static 'main/css/normalize.css' %}">
<link rel=stylesheet href="{% static 'main/css/main.css' %}">
{% block css %}{% endblock %}
</head>
<body>


<header>
  <div>
    <p id=title><a href="{% url 'main:main' %}">yibot</a></p>
  </div>
</header>

<div id=container>
  <div id=content>
    <div class=contentName>{% block contentName %}首頁{% endblock %}</div>
    
    {% block content %}
    {% endblock %}
    <br><br>
  </div>  <!-- content -->
  <div class=clear></div>
</div>  <!-- container -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
{% block script %}{% endblock %}

</body>
</html>